/**
 * Curated from common O*NET/ESCO skill-taxonomy categories (programming,
 * data/ML, cloud, design, hardware, business, and general professional
 * skills) rather than a live API call - keeps the autocomplete instant and
 * offline-capable instead of adding network latency/rate limits to typing.
 */
export const SKILL_POOL = [
  // Programming languages
  'Python',
  'Java',
  'JavaScript',
  'TypeScript',
  'C++',
  'C',
  'C#',
  'Go',
  'Rust',
  'Swift',
  'Kotlin',
  'R',
  'MATLAB',
  'SQL',
  'HTML/CSS',
  'PHP',
  'Ruby',
  'Scala',
  // Web & app frameworks
  'React',
  'Angular',
  'Vue.js',
  'Node.js',
  'Next.js',
  'Django',
  'Flask',
  'Spring Boot',
  '.NET',
  'React Native',
  'Flutter',
  // Data & machine learning
  'Data Analysis',
  'Machine Learning',
  'Deep Learning',
  'Natural Language Processing',
  'Computer Vision',
  'Data Visualization',
  'Statistical Analysis',
  'Data Engineering',
  'ETL Pipelines',
  'Pandas',
  'NumPy',
  'TensorFlow',
  'PyTorch',
  'Scikit-learn',
  'Tableau',
  'Power BI',
  'A/B Testing',
  // Cloud & DevOps
  'AWS',
  'Azure',
  'Google Cloud Platform',
  'Docker',
  'Kubernetes',
  'CI/CD',
  'Git',
  'Linux',
  'Terraform',
  'System Design',
  // Design
  'Figma',
  'Adobe Photoshop',
  'Adobe Illustrator',
  'Adobe XD',
  'Sketch',
  'UX Research',
  'UI Design',
  'Wireframing',
  'Prototyping',
  'Graphic Design',
  // Engineering & hardware
  'CAD',
  'SolidWorks',
  'AutoCAD',
  'Circuit Design',
  'PCB Design',
  'Embedded Systems',
  'Robotics',
  '3D Printing',
  'Simulink',
  'FEA Analysis',
  'Six Sigma',
  'Lean Manufacturing',
  // Business & finance
  'Excel Modeling',
  'Financial Modeling',
  'Valuation',
  'Accounting',
  'Bloomberg Terminal',
  'SAP',
  'Salesforce',
  'HubSpot',
  'QuickBooks',
  'Market Research',
  'Business Development',
  // Professional & soft skills
  'Project Management',
  'Public Speaking',
  'Leadership',
  'Negotiation',
  'Written Communication',
  'Customer Service',
  'Cross-functional Collaboration',
  'Agile/Scrum',
  'Problem Solving',
  'Critical Thinking',
  'Time Management',
  // Life sciences
  'Lab Techniques',
  'PCR',
  'Cell Culture',
  'Clinical Research',
  'Biostatistics',
  'CRISPR',
  // Legal & policy
  'Legal Research',
  'Contract Drafting',
  'Policy Analysis',
]

export const INTEREST_POOL = [
  'Software Engineering',
  'Product Management',
  'Data Science',
  'Machine Learning & AI',
  'UX/UI Design',
  'Hardware Engineering',
  'Robotics',
  'Cybersecurity',
  'Cloud Computing',
  'DevOps',
  'Finance',
  'Investment Banking',
  'Private Equity',
  'Venture Capital',
  'Accounting',
  'Consulting',
  'Management Consulting',
  'Marketing',
  'Sales',
  'Business Development',
  'Human Resources',
  'Supply Chain Management',
  'Operations',
  'Manufacturing',
  'Biotechnology',
  'Pharmaceuticals',
  'Healthcare',
  'Medical Devices',
  'Nonprofit Impact',
  'Sustainability',
  'Clean Energy',
  'Aerospace',
  'Automotive',
  'Telecommunications',
  'Retail',
  'E-commerce',
  'Real Estate',
  'Insurance',
  'Legal',
  'Education',
  'Government & Public Policy',
  'Media & Entertainment',
  'Gaming',
  'Hospitality & Tourism',
  'Agriculture',
  'Construction',
  'Energy & Oil',
  'Transportation & Logistics',
  'Fintech',
  'Edtech',
  'Healthtech',
  'Semiconductors',
  'Materials Science',
  'Chemical Engineering',
  'Civil Engineering',
  'Architecture',
  'Journalism',
  'Public Relations',
  'International Development',
  'Social Impact',
  'Quality Assurance',
  'Research & Development',
]
